name: Context Workflows
on:
    push:
        branches:
            - main

jobs:
    my-context:
        runs-on: ubuntu-latest
        steps:
            - name: "My step"
              run: |
                  echo "Hello $MY_ACTION"
                  echo "Actor is $MY_ACTOR"
              env:
                    MY_ACTION: ${{ github.action }}
                    MY_ACTOR: ${{ github.actor  }}


